name: HogeBankUiTests

on:
  workflow_dispatch:
    inputs:
      suite:
        description: 'Suite'
        required: false
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            
      - name: Run headless test
        id: tests
        uses: GabrielBB/xvfb-action@v1
        continue-on-error: true
        with:
          run: mvn clean test -Dheadless=true -Dgroups=${{ github.event.inputs.suite }}
      
      - name: Publish Test Report
        uses: starburstdata/action-testng-report@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Smoke Test Results
          path: target/surefire-reports/junitreports/*.xml
          reporter: java-junit
